apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-website-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Basty85/k8s-gitops-nginx-ha.git
    targetRevision: main
    path: helm-charts/nginx-website
    helm:
      valueFiles:
      - ../../environments/production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-hostname-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Basty85/k8s-gitops-nginx-ha.git
    targetRevision: main
    path: helm-charts/node-hostname
    helm:
      valueFiles:
      - values_security.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-management
  namespace: argocd  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Basty85/k8s-gitops-nginx-ha.git
    targetRevision: main
    path: cluster-management
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 5